### ISSUE TITLE
(n)listtree activates last entry click at bottom (free space)

### ISSUE THREAD

**Issue by javierdlr** [amiga-mui/nlist#1]
As I'm not sure if it's NListtree bug I added link to such ticket http://muidev.de/ticket/349

**Comment by tboeckel** [comment]
As you stated yourself, only NList/NListtree is affected, but not MUI's internal List/Listtree class. Hence this this the correct bug tracker.

I think I found the guilty check during the quite convoluted and far over-complex mouse click handling. Please try the attached version.
[NList_os3.zip](https://github.com/amiga-mui/nlist/files/957404/NList_os3.zip)
[NList_os4.zip](https://github.com/amiga-mui/nlist/files/957405/NList_os4.zip)

**Comment by javierdlr** [comment]
Tried OS4 version and almost ther, but when I click on bottom space the selected entry/item moves one position down (until it reaches last item on listtree).
Will reboot system and retest

**Comment by javierdlr** [comment]
Same issue even after a reboot.
See video attached, selection goes one down when I click on LMB, until end of listtree.
[output.zip](https://github.com/amiga-mui/nlist/files/958976/output.zip)


Not knowing about much about coding, maybe removing (commenting out) in NList_mcc2.c
'NL_List_Active(data,MUIV_NList_Active_Down,NULL,data->selectmode,FALSE,0);' (line 819 aprox) will avoid such "select down item".

**Comment by tboeckel** [comment]
The second version should fix this issue. At least I cannot make NList misbehave anymore, no matter where I click below the last entry.
[NList_os3.zip](https://github.com/amiga-mui/nlist/files/959523/NList_os3.zip)
[NList_os4.zip](https://github.com/amiga-mui/nlist/files/959522/NList_os4.zip)

**Comment by javierdlr** [comment]
YES!!!! Seems now fixed. THX A LOT!!
