### ISSUE TITLE
Nlist 0.123 crashes on MUI3.8

### ISSUE THREAD

**Issue by Doobrey** [amiga-mui/nlist#2]
Running OS3.9 and MUI 3.8 ,updated Nlist from 0.121 to 0.123 , now neither Scout or YAM start. Both crash with either 8000 0003 or 8000 0005 alerts.
The NList-Demo and NListree-Demo both run, but crash on exit (same alerts as above).

I've also tested with MUI5 (68k) and NList 0.123 and none of the above problems occur.

**Comment by tboeckel** [comment]
Please try the attached binaries. Please note that the version has not been bumped yet.

[NList.zip](https://github.com/amiga-mui/nlist/files/1630594/NList.zip)
[NListtree.zip](https://github.com/amiga-mui/nlist/files/1630595/NListtree.zip)

**Comment by Doobrey** [comment]
Thanks Thore, That seems to have fixed it under MUI 3.8.
