### ISSUE TITLE
64-bit fix

### ISSUE THREAD

**Issue by deadwood2** [amiga-mui/nlist#4]
Hello,

Please see the attached patch fixing a 64-bit issue.

[0003-64-bit-fix.patch.zip](https://github.com/amiga-mui/nlist/files/4772704/0003-64-bit-fix.patch.zip)

**Comment by jens-maus** [comment]
Thanks! But can‘t you simply fork this repo, integrate your patch and send over a pull request how this is done these days?!?

**Comment by jens-maus** [comment]
And where did you get it from? Please certify that you are allowed to send this patch and that you allow that it will be integrated as LGPL code in NList.

**Comment by deadwood2** [comment]
Hi, i'm the author of this patch and yes, I allow it to be integrated as LGPL code.

**Comment by deadwood2** [comment]
Ok, there are more 64-bit fixes. Closing this issues - I will fork and prepare pull requests.
